sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls
  - pip install -e .[test]
script:
  - pytest --cov=wagtailbakery --cov-report=xml
  - flake8 src/
after_success:
  - coveralls
