sudo: false
language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django22
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django20
    - python: 3.7
      env: TOXENV=py37-django21
    - python: 3.7
      env: TOXENV=py37-django22
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install coveralls tox
script:
  - tox -e $TOXENV
after_success:
  - coveralls
notifications:
  email: false
